### Upgrade a Lista de Entregas

In [12]:
from pathlib import Path
import pandas as pd
import json
import datetime as dt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
print('Importadas ok')

Importadas ok

In [13]:
carpeta = "../data/raw/"
file = carpeta + "clientes.parquet"

In [22]:
df_raw = pd.read_parquet(file)
df_raw.head()

,fecha_creacion,nombres,apellidos,tipo_documento,documento,genero,estado_civil,email,telefono,celulares,agrupacion_medio_captacion,medio_captacion,canal_entrada,nivel_interes,fecha_nacimiento,nacionalidad,pais,departamento,provincia,distrito,direccion,apto,observacion,ocupacion,documento_conyuge,usuario_creador,username,estado,ultimo_proyecto,total_unidades_asignadas,ultimo_vendedor,total_interacciones,fecha_ultima_interaccion,proyectos_relacionados,id,codigo_externo_cliente,rango_edad,origen,ultimo_tipo_interaccion,fecha_actualizacion,autorizacion_uso_datos,autorizacion_publicidad,geo_latitud,geo_longitud,geolocalizacion,cliente_riesgo,agrupacion_canal_entrada,tipo_persona,denominacion,tipo_financiamiento,desistido,razon_desistimiento,hora_creacion,fecha_primera_interaccion_manual,prioridad,uuid
0,2020-08-18,ANA DELIA,ESPINO PILLPE,DNI,auto-964705,Masculino,NaN,deliaespino82@hotmail.com,975170003,+51975170003,NaN,contacto web,llamada telefónica,por contactar,None,NaN,PE,LIM,NaN,NaN,NaN,Apto,NaN,NaN,NaN,NaN,NaN,Interesado,Sialia,0,Victor Salazar,8,2026-06-30,"NP,SL,TZ,CRUZ",30760,None,None,api,facebook,2026-06-30,True,False,None,None,None,no,None,Persona Natural,NaN,NaN,no,NaN,01:57:05,2023-09-11 20:18:12.103694,None,9b5af177-f48c4c-ed73
1,2026-06-18,Jorge,Arrelucea,DNI,auto-11818158104,Femenino,NaN,jarrelucefernandez@gmail.com,NaN,+51921201738,Digital,facebook,contacto web,por contactar,None,NaN,NaN,NaN,NaN,NaN,NaN,Apto,"s/70,000_a_más",NaN,NaN,NaN,NaN,Interesado,Campañas,0,NaN,2,2026-06-18,CAM,151543,None,None,fblead_ads,facebook,2026-06-18,True,False,None,None,None,no,None,Persona Natural,NaN,NaN,no,NaN,11:16:10,NaT,None,b9593f8c-4c170c-1177
2,2026-05-31,Luis,Lezameta,DNI,auto-2063323679,Femenino,NaN,lezametaroca79@gmail.com,NaN,+51947497507,Digital,facebook,contacto web,por contactar,None,NaN,NaN,NaN,NaN,NaN,NaN,Apto,2_dorm_desde_55.48_m2,NaN,NaN,NaN,NaN,Interesado,Torre Nápoles,0,NaN,3,2026-06-03,NP,149925,None,None,fblead_ads,llamada por teléfono,2026-06-03,True,False,None,None,None,no,None,Persona Natural,NaN,NaN,no,NaN,10:32:16,NaT,None,921fec00-e12716-976b
3,2026-06-18,sofia,uriarte,DNI,auto-128982,Femenino,soltero,suriarteva1@gmail.com,,+51965766611,NaN,paso por la zona,whatsapp,por contactar,None,peruvian,PE,LIM,Lima,NaN,,Apto,,,NaN,Mayra Nahui,mnahui,Interesado,Capadocia,0,NaN,2,2026-06-20,CP,151545,None,None,manual,whatsapp,2026-06-20,True,True,None,None,None,no,None,Persona Natural,,NaN,no,NaN,11:42:39,NaT,None,ddf9717c-10dbb5-16be
4,2026-06-18,Karol Milena,Añez Mondaca,DNI,auto-1542075611,Femenino,NaN,kami_am29@hotmail.com,NaN,+51937395480,Digital,facebook,contacto web,por contactar,None,NaN,NaN,NaN,NaN,NaN,NaN,Apto,3_dorm_desde_65.28_m2,NaN,NaN,NaN,NaN,Interesado,Capadocia,0,NaN,3,2026-06-22,CP,151537,None,None,fblead_ads,whatsapp,2026-06-22,True,False,None,None,None,no,None,Persona Natural,NaN,NaN,no,NaN,09:51:17,NaT,None,0de8e4b9-7704f2-d4cf

## Propietarios

In [38]:
df_propietarios = df_raw[df_raw['estado']=="Propietario"]
print(f'Total: {df_propietarios.shape[0]} clientes')
df_propietarios.sample(2)

Total: 1299 clientes

,fecha_creacion,nombres,apellidos,tipo_documento,documento,genero,estado_civil,email,telefono,celulares,agrupacion_medio_captacion,medio_captacion,canal_entrada,nivel_interes,fecha_nacimiento,nacionalidad,pais,departamento,provincia,distrito,direccion,apto,observacion,ocupacion,documento_conyuge,usuario_creador,username,estado,ultimo_proyecto,total_unidades_asignadas,ultimo_vendedor,total_interacciones,fecha_ultima_interaccion,proyectos_relacionados,id,codigo_externo_cliente,rango_edad,origen,ultimo_tipo_interaccion,fecha_actualizacion,autorizacion_uso_datos,autorizacion_publicidad,geo_latitud,geo_longitud,geolocalizacion,cliente_riesgo,agrupacion_canal_entrada,tipo_persona,denominacion,tipo_financiamiento,desistido,razon_desistimiento,hora_creacion,fecha_primera_interaccion_manual,prioridad,uuid
195,2026-06-30,Sonia Silvia,Chavez Sipiran,DNI,09614353,Femenino,soltero,schavezs_02@hotmail.com,NaN,+51924719407,NaN,facebook,llamada telefónica,por contactar,None,NaN,NaN,NaN,NaN,NaN,NaN,Apto,NaN,NaN,25611637,Fabricio Jean Pierre Torres Orellana,ftorres,Propietario,Alicanto,2,NaN,1,2026-06-30,GY,152213,None,None,manual,NaN,2026-06-30,True,False,None,None,None,no,None,Persona Natural,NaN,NaN,no,NaN,18:14:24,NaT,None,0c5ca1cf-b8b72d-d53c
102804,2024-01-08,-,VILLACORTA LAMAS ANTONIO JOSE,DNI,AUTO-907877,Femenino,NaN,NaN,NaN,NaN,Tradicional,caseta de ventas,visita presencial,dueño,None,NaN,NaN,NaN,NaN,NaN,NaN,Apto,NaN,NaN,NaN,Enzo Villanueva,evillanueva,Propietario,Edificio Saenz,2,Enzo Villanueva,4,2024-01-08,ES,105913,None,None,importación,visita al proyecto,2025-01-13,True,False,None,None,None,no,None,Persona Natural,NaN,NaN,no,NaN,12:14:00,2024-01-08 17:14:00,None,22e6f2a9-48ec0b-5f0c

### Col a Agregar

In [42]:
col_contacto = ['documento', 'celulares', 'email', 'telefono', 'nombres', 'apellidos']
df_propietarios = df_propietarios[col_contacto]
df_propietarios

,documento,celulares,email,telefono,nombres,apellidos
53,41326402,+33610760107,angemercado@gmail.com,,ANGEL EMANUEL,MERCADO ORDOÑEZ
194,20121877,+51937818236,yesys123443@gmail.com,,YESENIA MARLENY,PALOMINO VICTORIO
195,09614353,+51924719407,schavezs_02@hotmail.com,NaN,Sonia Silvia,Chavez Sipiran
204,18198498,+51959662977,jroxci2015@gmail.com,,JANETH ROXANA,CHUAN IBAÑEZ
224,70856177,+51934600185,ddinatale.r@gmail.com,,Diego,Di Natale
...,...,...,...,...,...,...
137089,19924826,+519000000000,hector.huamansamaniego@gmail.com,,Hector,Huaman Samaniego
137343,auto-163854481,+51998866123,jcffvip78@gmail.com,NaN,Juanca,Figueroa
137390,15347767,+51949232085,FRANKLINSUAREZG@GMAIL.COM,,FRANKLIN,SUAREZ GOMEZ
137546,auto-744984,NaN,l_cornejo@hotmail.com,,LIZARDO,CORNEJO
137547,40515819,+51964750008,Rijab.network@gmail.com,NaN,Ricardo,Acevedo

In [19]:
df.info()
#df.describe()
#df.()

<class 'pandas.DataFrame'>
RangeIndex: 137554 entries, 0 to 137553
Data columns (total 56 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   fecha_creacion                    137554 non-null  object
 1   nombres                           137554 non-null  str
 2   apellidos                         135915 non-null  str
 3   tipo_documento                    137554 non-null  str
 4   documento                         137554 non-null  str
 5   genero                            137554 non-null  str
 6   estado_civil                      26968 non-null   str
 7   email                             136815 non-null  str
 8   telefono                          38524 non-null   str
 9   celulares                         136990 non-null  str
 10  agrupacion_medio_captacion        84362 non-null   str
 11  medio_captacion                   136831 non-null  str
 12  canal_entrada                     134772 non-null  str
 13  nivel_interes                     132592 non-null  str
 14  fecha_nacimiento                  677 non-null     object
 15  nacionalidad                      21917 non-null   str
 16  pais                              113255 non-null  str
 17  departamento                      112839 non-null  str
 18  provincia                         37402 non-null   str
 19  distrito                          2197 non-null    str
 20  direccion                         21416 non-null   str
 21  apto                              137554 non-null  str
 22  observacion                       114148 non-null  str
 23  ocupacion                         21416 non-null   str
 24  documento_conyuge                 1176 non-null    str
 25  usuario_creador                   24165 non-null   str
 26  username                          24165 non-null   str
 27  estado                            137554 non-null  str
 28  ultimo_proyecto                   136422 non-null  str
 29  total_unidades_asignadas          137554 non-null  int64
 30  ultimo_vendedor                   116715 non-null  str
 31  total_interacciones               137554 non-null  int64
 32  fecha_ultima_interaccion          137490 non-null  object
 33  proyectos_relacionados            136422 non-null  str
 34  id                                137554 non-null  int64
 35  codigo_externo_cliente            0 non-null       object
 36  rango_edad                        0 non-null       object
 37  origen                            134964 non-null  str
 38  ultimo_tipo_interaccion           137158 non-null  str
 39  fecha_actualizacion               137554 non-null  object
 40  autorizacion_uso_datos            137554 non-null  bool
 41  autorizacion_publicidad           137554 non-null  bool
 42  geo_latitud                       0 non-null       object
 43  geo_longitud                      0 non-null       object
 44  geolocalizacion                   0 non-null       object
 45  cliente_riesgo                    137554 non-null  str
 46  agrupacion_canal_entrada          0 non-null       object
 47  tipo_persona                      137554 non-null  str
 48  denominacion                      26375 non-null   str
 49  tipo_financiamiento               13159 non-null   str
 50  desistido                         137554 non-null  str
 51  razon_desistimiento               234 non-null     str
 52  hora_creacion                     137554 non-null  str
 53  fecha_primera_interaccion_manual  89016 non-null   datetime64[us]
 54  prioridad                         0 non-null       object
 55  uuid                              137554 non-null  str
dtypes: bool(2), datetime64[us](1), int64(3), object(11), str(39)
memory usage: 92.2+ MB

In [21]:
df['estado'].value_counts()

estado
Interesado     136255
Propietario      1299
Name: count, dtype: int64

## Lista de Entregas
Fenix

In [44]:
carpeta = "../data/lista_entregas/"
file = carpeta + "CRONOGRAMA_ENTREGAS_FENIX_HARUMI.xlsx"

In [ ]:
df_entregas_raw = pd.ExcelFile(file)
print(f'Pestañas: {df_entregas_raw.sheet_names}')


df_entregas = pd.read_excel(file, sheet_name="CRONO-ORD-FECHA", skiprows=2)
print(f'Total: {df_entregas.shape[0]} clientes')
df_entregas.head()

Pestañas: ['CRONO-ORD-FECHA', 'CRONO-ORD-PISO', 'EN PROCESO', 'LIBRES']
Total: 39 clientes

,#,Tipo Unidad,N° Unidad,Comprador,DNI,Coprop. 1,DNI Cop. 1,Coprop. 2,DNI Cop. 2,Coprop. 3,DNI Cop. 3,Coprop. 4,DNI Cop. 4,F. Separación,F. Cancelación,Fecha Entrega\nPropuesta,Horario,Fecha Entrega\nEfectiva,Obs.
0,1.0,DEPARTAMENTO,1704,PERALTA VASQUEZ LISBETH SOFIA,45816592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16 Mar 2025,04 Sep 2025,20 Jul 2026,9:00 am,NaN,NaN
1,2.0,DEPARTAMENTO,904,MATTOS KINA MONICA PATRICIA,7990374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23 Ago 2025,04 Sep 2025,20 Jul 2026,11:00 am,NaN,NaN
2,3.0,DEPARTAMENTO,1503,DEL VALLE VARILLAS JOSUE HAMILTON,71300365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18 Ago 2025,12 Sep 2025,20 Jul 2026,2:00 pm,NaN,NaN
3,4.0,DEPARTAMENTO,1702,GARAY FLORES ROSMERY KAROL,47160251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04 Jun 2025,25 Sep 2025,20 Jul 2026,4:00 pm,NaN,NaN
4,NaN,ESTACIONAMIENTO,37,GARAY FLORES ROSMERY KAROL,47160251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12 Sep 2025,25 Sep 2025,20 Jul 2026,4:00 pm,NaN,NaN

### Merge con Sperant

In [ ]:
df_propietarios = documento
df_entregas_completo = df_entregas.merge(df_propietarios, how='left', on='DNI')